id: I3FDE541E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T12:36:36+00:00'
last_modified: '2022-06-09T17:45:32.899714+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W7732
  title: སུམ་པ་ཡེ་ཤེས་དཔལ་འབྱོར་གྱི་རང་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6D07:
      image_group_id: I1GS140299
      title: Volume 1 of ye shes dpal 'byor gyi rnam thar
      total_pages: 109
      order: 1
      base_file: 6D07.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
